### ISSUE TITLE
Utiliser sans serveur mail

### ISSUE THREAD

**Issue by aluneau** [comptasso/FaitesLesComptes#22]
Bonjour tout le monde :)
je viens de trouver votre logiciel qui a l'air pile poil de correspondre avec ce que je veux!
je l'ai installé seulement je n'ai pas de serveur mail et je n'ai pas envie d'en installer un car je serais tout seul à l'utiliser sur ma machine...
Y a t'il possibilité dans la conf de dire que l'utilisateur est directement inscrit ? 

je suis bloqué à cause de ça car j'ai pas moyen de récuperer le mail d'activation du coup...

**Comment by comptasso** [comment]
Ce n'est pas prévu et il n'y a donc pas de solution facile.
Il faut donc rentrer dans le programme en allant dans le répertoire (en mode console) où il a été installé et en tapant:
`rails c` ce qui veut dire de faire fonctionner rails en mode console
Normalement, vous n'aurez qu'un seul user qui aura l'identifiant 1. 
Vous pouvez le vérifier en tapant `User.all`qui vous affichera la liste des users. Supposons effectivement qu'il n'y a qu'un seul user avec l'identifiant (id) 1. Pour pouvoir intervenir sur cet user, vous devez taper:
u = User.find 1
Désormais vous pouvez agir sur cet user et taper
`u.confirmed_at` = Time.now
`u.valid?` (pour vérifier que tout va bien)
`u.save` (pour le sauver)
Vous pouvez maintenant sortir de rails en faisant `quit` (ou `exit`, j'ai un doute). 

Il existe une autre méthode qui consiste à aller dans les logs trouver le texte du mail qui a été produit, et donc le lien envoyé. Copier ce lien dans la fenêtre du navigateur. C'est alors comme si vous aviez reçu le mail et cliqué sur le lien transmis. 
Je pense que la première méthode ci-dessus est un peu plus facile. 

N'hésitez pas à m'écrire si ça ne suffit pas.

**Comment by aluneau** [comment]
Ok merci beaucoup ça fonctionne nickel cette méthode c'était exactement ce que je cherchais à faire ! :)
